apiVersion: v1
kind: Secret
metadata:
  name: seguros-producto-gestionarproducto-secrets
  namespace: backend
data:
  springCloudConfigServerPath: aHR0cDovL3NlZ3Vyb3MtdGktc3ByaW5nLWNsb3VkLWNvbmZpZy1zZXJ2ZXIubWlkZGxld2FyZS5zdmMuY2x1c3Rlci5sb2NhbDo4MDgw
  swaggerBasePath: YXBpLXByb3h5LXVhdC5hZHJmc2MuY2wvZ2VzdGlvbmFyUHJvZHVjdG8=  
